package me.omartanner.modulepal.api.auth.error;

public enum MemberDataStorerErrorType {
    NO_STUDENT_COURSE_DETAILS,
    NO_HOME_DEPARTMENT,
//    FAILED_TO_POPULATE_MODULE_REGISTRATION_INDEXES,
//    FAILED_TO_WRITE_MODULE_REGISTRATION_BASIC_DATA,
    FAILED_TO_WRITE_MODULE_REGISTRATION_BASIC_DATA_OR_INDEXES,
    FAILED_TO_WRITE_UNI_USER_BASIC_DATA
}
